Revert broken commit "Try to solve some optimisation issue with br used for calls"
This reverts commit e728ff9a609218d9c4b8b18c206b8079c38881e3.

error type on process().program()->findSymbol(taa);
```
8.301 /home/statinf/otawa-project/archs/otawa-aarch64/aarch64.cpp:879:80: error: cannot convert 'otawa::address_t' {aka 'otawa::Address'} to 'elm::String'
8.301   879 |                         otawa::Symbol *tsymb = process().program()->findSymbol(taa);
8.301       |                                                                                ^~~
8.301       |                                                                                |
8.301       |                                                                                otawa::address_t {aka otawa::Address}
```